// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller.js"
application.register("alert", AlertController)

import AutocompleteController from "./autocomplete_controller.js"
application.register("autocomplete", AutocompleteController)

import DragController from "./drag_controller.js"
application.register("drag", DragController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import LottieController from "./lottie_controller.js"
application.register("lottie", LottieController)
