meta_product_name: "Claps"
meta_title: "Claps"
meta_description: "A mobile apps to search movies with your friends or solo"
meta_image: "Dashboard-card.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
