meta_product_name: "Claps"
meta_title: "Claps - Movie finder (JD AM JADC MR)"
meta_description: "A mobile apps to search movies with your friends or solo"
meta_image: "og-meta-image.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
